name: Build and Deploy

on:
  push:
    branches: [main]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

jobs:
  build:
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

jobs:
  build:
    steps:
      - name: Build
        run: |
          npm ci
          npm run build
jobs:
  build:
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REACT_SAMPLE_TOKEN }}
          publish_dir: ./build
